### ISSUE TITLE
 Unknown argument  "userId" on field "feeds" of type "RootQuery".

### ISSUE THREAD

**Issue by BhaskaranR** [apollographql/apollo-angular#315]
I am getting this  error **sporadically** with my angular apollo client. I did verify the userId and it is passed in correctly. i copied the same query with graphiql and it works every time. 
when i get this error the request doesn't even make it to the  server, so i guess this something wrong with the angular UI. Moreover i am using apollo with ngrx.  Appreciate any help

```
core.es5.js:1084 ERROR Error: GraphQL error: Unknown argument "userId" on field "feeds" of type "RootQuery".
    at new ApolloError (http://localhost:4201/vendor.bundle.js:71141:28)
    at http://localhost:4201/vendor.bundle.js:138673:41
    at http://localhost:4201/vendor.bundle.js:139108:25
    at Array.forEach (native)
    at http://localhost:4201/vendor.bundle.js:139105:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (http://localhost:4201/vendor.bundle.js:139102:42)
    at Array.<anonymous> (http://localhost:4201/vendor.bundle.js:138472:23)
    at Object.dispatch (http://localhost:4201/vendor.bundle.js:79113:19)
    at dispatch (<anonymous>:2:31875)
```
Please click this link to check the issue discussed in detail

https://apollographql.slack.com/files/bhaskar/F5N856Z51/screen_shot_2017-06-03_at_9.20.05_pm.png

https://apollographql.slack.com/archives/C0Z9ZBDF0/p1496545444511183

https://apollographql.slack.com/files/bhaskar/F5P5F459D/screen_shot_2017-06-03_at_11.28.54_pm.png

**Comment by BhaskaranR** [comment]
found the issue. it is my bad. i was running another instance with the old source and was load balancing the instances with rabbitmq. some requests are sent to the this other instance.
