### ISSUE TITLE
'token import' error when deploying to Firebase using Cloud Functions

### ISSUE THREAD

**Issue by drejohnson** [apollographql/apollo-angular#361]
```
Error: Error occurred while parsing your function triggers.

/tmp/fbfn_28981T48ASTQ0re6m/node_modules/apollo-angular/build/src/tokens.js:1
(function (exports, require, module, __filename, __dirname) { import { OpaqueToken } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.WVKj (/tmp/fbfn_28981T48ASTQ0re6m/dist-ssr/main.bundle.js:1:10087)
```

**Comment by DarrienG** [comment]
Any updates? Did you ever get this working?

**Comment by kamilkisiela** [comment]
There are two ways `apollo-angular` distribute code.

- umd bundle - `"main": "bundle.umd.js"`
- ES5 + ESM - `"module": "index.js"`

Somehow the second option is taken.

Could you create a simple reproduction so I can see what might be the reason?

**Comment by DarrienG** [comment]
Hey there. Turns out it was an unrelated issue. Just me not getting enough sleep and forgetting some packages. Cheers!
