### ISSUE TITLE
500 Internal Server error after attaching Bearer token for authentication

### ISSUE THREAD

**Issue by joaogarin** [apollographql/apollo-angular#458]
Hello,

I have an app I am working on, everything works fine but as soon as I attach a token for authentication I get a 500 Internal server error.

The queries and mutations all are working properly in graphiql explorer (in my server) but from Apollo if the auth token attached I get : 

```
/vetkey/vetkeycms/web/graphql Failed to load resource: the server responded with a status of 500 (Internal Server Error)
(unknown) DOMException: Failed to execute 'postMessage' on 'Window': function () {
                _this.headers = new Map();
                headers.split('\n').forEach(function (...<omitted>... } could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:14:14)
    at QueryManager.onBroadcast (http://localhost:4200/vendor.bundle.js:4232:27)
    at QueryManager.webpackJsonp.../../../../apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:4200/vendor.bundle.js:5308:14)
    at http://localhost:4200/vendor.bundle.js:4877:31
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2937:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:67320:33)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2936:32)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (http://localhost:4200/polyfills.bundle.js:2687:43)
    at http://localhost:4200/polyfills.bundle.js:3418:57
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2970:31)
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Network error: Http failure response for http://localhost/vetkey/vetkeycms/web/graphql: 500 Internal Server Error
Error: Network error: Http failure response for http://localhost/vetkey/vetkeycms/web/graphql: 500 Internal Server Error
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:277
    at QueryManager.js:664
    at Array.forEach (<anonymous>)
    at QueryManager.js:663
    at Map.forEach (<anonymous>)
    at QueryManager.webpackJsonp.../../../../apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (QueryManager.js:658)
    at QueryManager.js:226
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.es5.js:3890)
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:277
    at QueryManager.js:664
    at Array.forEach (<anonymous>)
    at QueryManager.js:663
    at Map.forEach (<anonymous>)
    at QueryManager.webpackJsonp.../../../../apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (QueryManager.js:658)
    at QueryManager.js:226
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.es5.js:3890)
    at resolvePromise (zone.js:824)
    at zone.js:876
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1566)
defaultErrorLogger @ core.es5.js:1020
/vetkey/vetkeycms/web/graphql:1 POST http://localhost/vetkey/vetkeycms/web/graphql 500 (Internal Server Error)
ApolloClient.js:133 DOMException: Failed to execute 'postMessage' on 'Window': function () {
                _this.headers = new Map();
                headers.split('\n').forEach(function (...<omitted>... } could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:14:14)
    at QueryManager.onBroadcast (http://localhost:4200/vendor.bundle.js:4232:27)
    at QueryManager.webpackJsonp.../../../../apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:4200/vendor.bundle.js:5308:14)
    at Object.error (http://localhost:4200/vendor.bundle.js:4771:27)
    at SubscriptionObserver.error (http://localhost:4200/vendor.bundle.js:28727:19)
    at SubscriptionObserver.error (http://localhost:4200/vendor.bundle.js:28727:19)
    at Object.error (http://localhost:4200/vendor.bundle.js:2621:61)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:18082:16)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.error (http://localhost:4200/vendor.bundle.js:18041:26)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._error (http://localhost:4200/vendor.bundle.js:17972:26)
Subscriber.js:238 Error: Network error: Http failure response for http://localhost/vetkey/vetkeycms/web/graphql: 500 Internal Server Error
    at new ApolloError (ApolloError.js:34)
    at Object.error (QueryManager.js:122)
    at SubscriptionObserver.error (zen-observable.js:174)
    at SubscriptionObserver.error (zen-observable.js:174)
    at Object.error (HttpLink.js:82)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.error (Subscriber.js:197)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._error (Subscriber.js:128)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.error (Subscriber.js:102)
    at FilterSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._error (Subscriber.js:128)
```

This is what the main module looks like : 

```
export class AppModule {
  constructor(apollo: Apollo,
    httpLink: HttpLink,
    private httpclient: HttpClient) {
    const http = httpLink.create({ uri: `${environment.contenta_url}${environment.graphql}` });

    const auth = setContext((_, { headers }) => {
      // get the authentication token from local storage if it exists
      const token = localStorage.getItem('token');

      if (!token) {
        return {};
      } else {
        return {
          headers: new HttpHeaders().append('Authorization', `Bearer ${token}`)
        };
      }
    });

    apollo.create({
      link: auth.concat(http),
      cache: new InMemoryCache(),
    });
  }
}

```

This is how the request looks like : 

<img width="1437" alt="screen shot 2018-01-01 at 18 15 35" src="https://user-images.githubusercontent.com/2866604/34469950-cc2eb3d6-ef1f-11e7-99ae-01b20d394c75.png">

Does anyone have any advice on how to debug what might be going on?

Thank you!

**Comment by joaogarin** [comment]
In the example in the docs it does this : 

```
const auth = setContext((_, { headers }) => {
      // get the authentication token from local storage if it exists
      const token = localStorage.getItem('token');
      // return the headers to the context so httpLink can read them
      // in this example we assume headers property exists
      // and it is an instance of HttpHeaders
      if (!token) {
        return {};
      } else {
        return {
          headers: headers.append('Authorization', `Bearer ${token}`)
        };
      }
    });
```

However "headers" is undefined when I do this, and thats why I set my headers directly in there. maybe some other header should be included?

**Comment by intellix** [comment]
I'm seeing the auth token included in your request, so it looks like everything is working correctly as far as I can see from Apollo's side. 500 error means there's a server error which needs addressing regardless I think.

The only difference between graphiql and apollo is that the Auth token is being sent right? If you Copy both requests as cURL and compare them. I think your server doesn't handle the token correctly and Apollo isn't doing anything special as you'll see when comparing.

Try Copy as cURL the Apollo query and remove the Authorization Header from the request and see if it works I think

**Comment by joaogarin** [comment]
Thanks for the answer I will try it out! I will close the issue as it seems it unrelated to apollo at all

Thanks for the help ;)

**Comment by jalloh-codes** [comment]
hello, @joaogarin was you able to solve it. I have the same problem.
