### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by jonasarcangel** [apollographql/apollo-angular#745]
I'm getting the following error:

```
SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

The error is from: node_modules/apollo-angular/ApolloModule.js:1 (function (exports, require, module, __filename, __dirname) { import { NgModule } from '@angular/core';

The complete code is at:
https://github.com/jonasarcangel/ModuleIssue

**Comment by jonasarcangel** [comment]
This is with dotnet core.

It happens when using "dotnet run" and navigating to any route. It does not
happen when I run in ClientApp folder using "npm run build:ssr && npm run
start".

**Comment by kamilkisiela** [comment]
@jonasarcangel Could you check v1.2.0? We switched to use ng-packagr

**Comment by kamilkisiela** [comment]
I guess I can close it
https://github.com/kamilkisiela/apollo-angular-ssr/tree/ts-node
